export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const COUNT_VIEW_PRODUCT_SUCCESS="COUNT_VIEW_PRODUCT_SUCCESS";
export const LOAD_USERS_SUCCESS="LOAD_USERS_SUCCESS";
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";